---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: director-state-file
  - name: bosh-cpi-release
  - name: published-bosh-cpi-release
  - name: bosh-init
  - name: bosh-release
  - name: stemcell
run:
  path: bosh-cpi-release/ci/tasks/deploy-e2e-director.sh
params:
  BOSH_INIT_LOG_LEVEL:            warn
  dns:                            replace-me
  v3_e2e_flavor:                  replace-me
  v3_e2e_connection_timeout:      replace-me
  v3_e2e_read_timeout:            replace-me
  v3_e2e_state_timeout:           replace-me
  v3_e2e_write_timeout:           replace-me
  bosh_openstack_ssl_verify:      replace-me
  bosh_director_username:         replace-me
  bosh_director_password:         replace-me
  v3_e2e_bosh_registry_port:      replace-me
  v3_e2e_api_key:                 replace-me
  v3_e2e_auth_url:                replace-me
  v3_e2e_default_key_name:        replace-me
  v3_e2e_floating_ip:             replace-me
  v3_e2e_manual_ip:               replace-me
  v3_e2e_net_cidr:                replace-me
  v3_e2e_net_gateway:             replace-me
  v3_e2e_net_id:                  replace-me
  v3_e2e_security_group:          replace-me
  v3_e2e_project:                 replace-me
  v3_e2e_domain:                  replace-me
  v3_e2e_username:                replace-me
  v3_e2e_private_key_data:        replace-me
  v3_e2e_blobstore_bucket:        replace-me
  v3_e2e_blobstore_host:          replace-me
  v3_e2e_blobstore_access_key:    replace-me
  v3_e2e_blobstore_secret_key:    replace-me
