---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: openstack-lifecycle-stemcell
outputs:
  - name: output
run:
  path: bosh-cpi-src-in/ci/tasks/run-lifecycle.sh
params:
  BOSH_OPENSTACK_DOMAIN:                   ""
  BOSH_OPENSTACK_AUTH_URL_V2:              ""
  BOSH_OPENSTACK_USERNAME_V2:              ""
  BOSH_OPENSTACK_API_KEY_V2:               ""
  BOSH_OPENSTACK_AUTH_URL_V3:              ""
  BOSH_OPENSTACK_USERNAME_V3:              ""
  BOSH_OPENSTACK_API_KEY_V3:               ""
  BOSH_OPENSTACK_PROJECT:                  ""
  BOSH_OPENSTACK_TENANT:                   ""
  BOSH_OPENSTACK_MANUAL_IP:                ""
  BOSH_OPENSTACK_NO_DHCP_MANUAL_IP_1:      ""
  BOSH_OPENSTACK_NO_DHCP_MANUAL_IP_2:      ""
  BOSH_OPENSTACK_NET_ID:                   ""
  BOSH_OPENSTACK_NET_ID_NO_DHCP_1:         ""
  BOSH_OPENSTACK_NET_ID_NO_DHCP_2:         ""
  BOSH_CLI_SILENCE_SLOW_LOAD_WARNING:      ""
  BOSH_OPENSTACK_VOLUME_TYPE:              ""
  BOSH_OPENSTACK_CONNECT_TIMEOUT:          ""
  BOSH_OPENSTACK_READ_TIMEOUT:             ""
  BOSH_OPENSTACK_WRITE_TIMEOUT:            ""
  BOSH_OPENSTACK_DEFAULT_KEY_NAME:         ""
  BOSH_OPENSTACK_CA_CERT:                  ""
  BOSH_OPENSTACK_FLAVOR_WITH_NO_ROOT_DISK: ""
