---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-cpi-dev-artifacts
  - name: bosh-director-deployment
  - name: bosh-init
  - name: stemcell
  - name: bosh-release
  - name: version-semver
run:
  path: bosh-cpi-src-in/ci/tasks/teardown-director.sh
params:
  bosh_admin_password:     ""
  bosh_director_ip:        ""
