---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-release
  - name: bosh-cpi-release
  - name: stemcell
outputs:
  - name: certification-receipt
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/generate-certification.sh
params:
  bosh_release_name: replace-me
  cpi_release_name:  replace-me
  stemcell_name:     replace-me
