
---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-init
  - name: bosh-release
  - name: bosh-cpi-release
  - name: stemcell
  - name: upgrade-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/teardown.sh
