---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-cpi-release
  - name: bosh-init
  - name: bosh-release
  - name: stemcell
  - name: deployment
  - name: terraform
outputs:
  - name: upgrade-deployment
run:
  path: bosh-cpi-src-in/ci/pipelines/certify-stemcell/tasks/test-upgrade.sh
params:
  BOSH_INIT_LOG_LEVEL:                 warn
  bosh_admin_password:                 replace-me
  v3_e2e_flavor:                       replace-me
  v3_e2e_connection_timeout:           replace-me
  v3_e2e_read_timeout:                 replace-me
  v3_e2e_state_timeout:                replace-me
  v3_e2e_write_timeout:                replace-me
  bosh_openstack_ca_cert:              replace-me
  v3_e2e_bosh_registry_port:           replace-me
  v3_e2e_api_key:                      replace-me
  v3_e2e_auth_url:                     replace-me
  v3_e2e_project:                      replace-me
  v3_e2e_domain:                       replace-me
  v3_e2e_username:                     replace-me
  v3_e2e_private_key_data:             replace-me
  time_server_1:                       replace-me
  time_server_2:                       replace-me
  distro:                              replace-me
